name: Naukri Resume Updater

description: >
  Automates login to Naukri.com and updates the resume with the provided PDF file.

author: M Swarna Priya

credentials:
  username: "priyaswarna369@gmail.com"
  password: "Google@1234"  # ⚠ Consider using environment variables or secrets in production

resume:
  file_name: "Swarna Priya 6.9Years of exp.pdf"
  file_path: "C:/Users/ASUS/OneDrive/Documents/test/naukri_auto_upload-main/Swarna Priya 6.9Years of exp.pdf"

selenium:
  driver: "chrome"
  driver_manager: true
  options:
    - "--start-maximized"
  wait_timeout: 20

urls:
  login: "https://www.naukri.com/nlogin/login"
  profile: "https://www.naukri.com/mnjuser/profile?id=&orgn=homepage"

actions:
  - step: Login to Naukri
    elements:
      username_field: { by: "id", value: "usernameField" }
      password_field: { by: "id", value: "passwordField" }
      login_button: { by: "xpath", value: "//button[text()='Login']" }

  - step: Delete existing resume if found
    elements:
      existing_resume: { by: "xpath", value: "//*[contains(text(),'Swarna Priya 6.9Years of exp.pdf')]" }
      delete_icon: { by: "xpath", value: "//i[@title='Click here to delete your resume']" }
      confirm_delete: { by: "xpath", value: "//div[@class='lightbox model_open flipOpen']//button[@class='btn-dark-ot'][normalize-space()='Delete']" }

  - step: Upload new resume
    elements:
      update_resume_button: { by: "xpath", value: "//em[text()='Update resume'] | //button[contains(text(),'Update Resume')]" }
      file_input: { by: "xpath", value: "//input[@type='file']" }
      success_message: { by: "xpath", value: "//div[contains(text(),'Resume uploaded successfully')]" }

logging:
  success_message: "✅ Resume updated successfully!"
  error_message: "❌ An error occurred"

